import random

import pandas as pd

INVERSED = [
  "330684",
  "330697",
  "330699",
  "330718",
  "333015",
  "333017",
  "333020",
  "333021",
  "333022",
  "333036",
  "374142",
  "374143",
  "374149",
  "374177",
  "374196",
  "TCGA-13-0799",
  "TCGA-13-0904",
  "TCGA-13-1405",
  "TCGA-13-1488",
  "TCGA-13-1499",
  "TCGA-13-1507",
  "TCGA-13-1511",
  "TCGA-24-1614",
  "TCGA-61-1906",
  "TCGA-61-2016",
  "TCGA-13-0724",
]

annotations = {
  "330680": "Grosse tumeur avant/droite, très petite métastase avant/droite",
  "330681": "Moyenne tumeur primaire centrale [PAS DE METASTASE]",
  "330682": "Grosse tumeur centrale, moyenne métastase étendue avant/droite",
  "330683": "Grosse tumeur centrale, métastase moyenne avant",
  "330684": "[CI] Petite tumeur centrale centrale [PAS DE METASTASE]",
  "330685": "Deux petits cancers primaires centraux [PAS DE METASTASE]",
  "330686": "[C] Grosses et petites métastases éparpillées devant [PAS DE PRIMAIRE]",
  "330687": "Grosses métastase devant [PAS DE PRIMAIRE]",
  "330688": "Grosse tumeur centrale/devant, métastases devant une pour chaque coté (droite/gauche)",
  "330689": "Enorme tumeur centrale, métastase moyenne coté droit",
  "330690": "[C] Une moyenne tumeur devant se séparant en deux, petite métastase devant",
  "330693": "2 petites tumeurs au centre, 2 moyennes métastases devant et à gauche",
  "330696": "[C] 2 moyenne tumeurs au centre, une métastase étendue sur tout le devant",
  "330697": "[I] grosse tumeur centrale et grosse métastase devant",
  "330698": "2 moyenne tumeurs au centre, une métastase étendue sur le devant",
  "330699": "[I] 2 moyenne tumeurs au centre, une métastase étendue sur tout le devant",
  "330700": "[C] 2 moyenne tumeurs au centre, une métastase étendue devant à droite",
  "330701": "[C] Grosse tumeur centrale [PAS DE METASTASE]",
  "330702": "[C] Moyenne tumeur primaire centrale, petite métastase devant à gauche",
  "330704": "[C] 2 moyennes tumeurs au centre, métastase étendue sur le coté droit",
  "330705": "Grosse tumeur centrale [PAS DE METASTASE]",
  "330707": "[C] 2 tumeurs moyennes au centre, légère métastase étendue sur le coté droit",
  "330708": "[C] 2 tumeurs moyennes au centre, légères métastases étendues sur le coté droit",
  "330710": "[C] Grosse tumeur à droite et moyenne tumeur à gauche, petites métastases dispersées à droite",
  "330711": "2 petites tumeurs au centre, métastase étendue devant/à droite",
  "330713": "[C] 2 petites tumeurs au centre, très petite métastase devant",
  "330717": "Grosse tumeur centrale [PAS DE METASTASE]",
  "330718": "[CI] Grosse tumeur centrale, très petite métastase devant et une autre petite métastase à droite plus haut dans le corps",
  "330719": "2 moyennes tumeurs au centre, plein de métastase sur le devant",
  "333005": "[C] Grosse tumeur centrale, grosse métastase étendue tout sur le devant",
  "333007": "[C] Très grosse tumeur centrale, grosse métastase étendue sur tout le devant",
  "333008": "[C] Très grosse tumeur centrale, grosse métastase étendue sur tout le devant",
  "333009": "Grosse tumeur centrale gauche, moyenne tumeur centrale droite, métastases devant à gauche",
  "333010": "Très petite tumeur centrale droite [PAS DE METASTASE]",
  "333011": "Métastase étendue sur le devant [PAS DE PRIMAIRE]",
  "333012": "[C] Métastase étendue sur le devant [PAS DE PRIMAIRE]",
  "333013": "2 tumeurs au centre, une gauche et l'autre droite, grosse métastase étendue sur tout le devant / droite",
  "333015": "[IC] Petite tumeur centrale [PAS DE METASTASE]",
  "333017": "[IC] Tumeur centrale coupée en 2 parties, très petite métastase devant à droite",
  "333020": "[IC] (Gros cut dans la donnée) grosse métastase étendue sur tout le devant [PAS DE PRIMAIRE]",
  "333021": "[IC] Moyenne tumeur centrale, 2 petites métastases gauche/droite devant",
  "333022": "[I] Grosse tumeur primaire centre/gauche et petite à droite",
  "333026": "Grosse tumeur centrale, grosse métastase étendue sur la gauche vers le devant",
  "333027": "[C] Grosse tumeur centrale, métastases étendues tout devant vers la droite",
  "333028": "[C] Métastase devant à droite [PAS DE PRIMAIRE]",
  "333031": "[C] Grosse tumeur centrale gauche, petite tumeur centrale droite, métastase devant",
  "333033": "[C] 2 petites tumeurs au centre, métastase devant à gauche",
  "333035": "[C] 1 petite tumeur centre/gauche, 1 grosse tumeur centre/droite [PAS DE METASTASE]",
  "333036": "[IC] Métastases à droite et devant [PAS DE PRIMAIRE]",
  "333037": "[C] 2 petites tumeurs centrales, grosses métastases devant et au centre",
  "333039": "[C] petite/moyenne métastase à droite [PAS DE PRIMAIRE]",
  "333041": "[C] Grosse tumeur centrale, très petite métastase devant à droite",
  "333042": "Grosse tumeurs au centre, et une à petite à gauche, très petite métastase devant",
  "333043": "[C] Métastase étendue devant [PAS DE PRIMAIRE]",
  "333044": "[C] Grosse tumeur centrale, moyenne métastase à droite",
  "333046": "Petite métastase devant [PAS DE PRIMAIRE]",
  "333047": "[C] Enorme tumeur dans tout l'organe, et petite métastase devant",
  "333051": "[C] Tumeur et métastase moyennes à gauche",
  "333056": "[C] Petite tumeur centrale et moyenne métastase étendue sur tout le devant",
  "333057": "[C] Grosse tumeur au centre à droite, métastase moyenne à droite",
  "333058": "Petite tumeur centrale, métastase moyenne étendue à droite",
  "333060": "[C] Grosse métastase étendue devant [PAS DE PRIMAIRE]",
  "333063": "[C] 2 tumeurs moyenne à gauche et à droite, petite métastase devant à droite",
  "333064": "Petite tumeur primaire centre gauche [PAS DE METASTASE]",
  "333065": "[C] Grosse métastase étendue à gauche [PAS DE PRIMAIRE]",
  "333067": "Petote métastases devant [PAS DE PRIMAIRE]",
  "333068": "[C] Moyenne tumeur primaire centrale/derriere, moyenne métastase à gauche, grosse métastase étendue à droite",
  "333069": "[C] Tumeur moyenne centrale [PAS DE METASTASE]",
  "333070": "[C] Grosse tumeur centrale, grosse métastase étendue sur le devant/droite",
  "333073": "Deux tumeurs primaires moyennes, grosses et petites métastases étendues devant à droite",
  "333075": "[C] 2 petites tumeurs primaires [PAS DE METASTASE]",
  "333076": "(Problèmes de tailles de slices dans la données) Tumeur centrale qui se sépare en 2, moyenne métastase étendue sur le devant à droite",
  "333077": "Tumeur centrale moyenne [PAS DE METASTASE]",
  "333081": "2 petites tumeurs au centre, métastase à droite",
  "333083": "Grosse tumeur à gauche, petite métastase à gauche",
  "333084": "[C] Moyenne métastase du centre vers la droite [PAS DE PRIMAIRE]",
  "333087": "[C] Petite tumeur centrale, grosse métastase étendue sur tout le devant",
  "333482": "2 moyennes métastases devant devant et à droite [PAS DE PRIMAIRE]",
  "333483": "2 tumeurs centrales, petite métastase à droite",
  "334149": "[C] Petite métastase à droite [PAS DE PRIMAIRE]",
  "334150": "Moyenne métastase étendu du devant vers la gauche [PAS DE PRIMAIRE]",
  "334940": "[C] Petite tumeur au centre à droite, grosse métastase étendu devant et sur le coté droit",
  "337189": "Moyenne métastase étendue sur le devant et une petité métastase à droite [PAS DE PRIMAIRE]",
  "337192": "Une tumeur moyenne Q3 et une petite tumeur Q4, une grosse metastase etendue / bicorne Q1-Q2 en haut",
  "337193": "Une moyenne-grosse tumeur etendue en bas Q3, une petite metastase en Q2 au meme niveau et une autre petite metastase en Q1 un peu plus haut",
  "337197": "Une petite tumeur a la gauche hauteur milieu, [PAS DE METASTASES]",
  "337198": "Une petite tumeur en bas Q2, une grosse metastase en haut Q2",
  "337199": "Une moyenne-grosse tumeur Q3 haut, 1 grosse metastase etendue Q1-Q2 bifurquant vers le haut",
  "337202": "Deux tumeurs moyennes Q3 et Q4, deux grosses metastases Q1 vraiment haut",
  "337203": "Une petite tumeur Q1, une grosse metastases etendue Q1-Q2",
  "337204": "Deux petites tumeurs Q3 et Q4, une grosse metastase etendue Q2 et une metastase moyenne Q1-Q4",
  "337205": "Une tumeur moyenne Q1/centre, 3 petites metastases Q2 avant et une metastase moyenne Q1",
  "347439": "Deux tumeurs moyenne-petites Q2-Q3 et Q1-Q4 resp., une metastase moyenne Q2",
  "347440": "Une tumeur moyenne-grosse Q4, une metastase moyenne alongee Q1",
  "347441": "Une tumeur moyenne-grosse Q4 arriere, une petite metastase Q1 devant",
  "347443": "Deux tumeurs moyenne Q1-Q4 et Q2-Q3 resp, une metastase moyenne-grosse Q1",
  "347444": "[PAS DE PRIMAIRES], une grosse metastase Q1",
  "347446": "Grosse tumeur Q3 posterieur et une moyenne-grosse Q1-Q4, une petite metastase Q2 vraiment devant",
  "347447": "Une tumeur Godzilla Q2-Q3-Q4 et un peu Q1, une grosse metastase Q1 devant",
  "347448": "Une grosse tumeur Q2 et une tumeur moyenne Q1, une metastase moyenne Q1 devant",
  "347451": "Une tumeur Godzilla Q1 et centre de l'anterieur au posterieur, [PAS DE METASTASES]",
  "347452": "Une grosse tumeur Q3, [PAS DE METASTASES] -- Trucs filandreux autours du corps peut-etre des habits ?",
  "347455": "Une tumeur moyenne Q1-Q4 bas du corps, [PAS DE METASTASES]",
  "347456": "Deux tumeurs moyennes Q3 et Q4, une grosse metastase Q2 et une grosse etendue en Q1 -- Artefacts lumineux autour du corps",
  "347458": "Une tumeur moyenne au centre, une grosse metastase etendue en Q1 devant-droit et une moyenne en Q1-Q4",
  "347463": "[PAS DE PRIMAIRES], une grosse metastase Q2 -- os de jambes tres lumineux",
  "347467": "Une tumeur Godzilla en Q3-Q4, une metastase mini-Godzilla en Q1",
  "347469": "Une grosse tumeur Q2 et une moyenne en Q1, une metastase mini-Godzilla en Q1-Q2",
  "347470": "Une tumeur Godzilla++ partout, une metastase petite-moyenne Q1 avant",
  "347471": "Deux tumeurs moyennes Q1 et Q2, une metastase moyenne en Q2",
  "347473": "Une tres grosse tumeur au centre, une petite metastase en Q1 avant -- lumieure autour corps haut de l'image",
  "347483": "Une tumeur Godzilla++ partout, une metastase moyenne-petite en Q1-Q4",
  "347485": "Une grosse tumeur en Q1-Q4, [PAS DE METASTASES]",
  "347490": "Une grosse tumeur centre-Q2-Q3 et une tumeur moyenne centre-Q1-Q4, une metastase moyenne en Q1 avant -- lumiere autour corps au niveau de la metastase",
  "347492": "Deux grosses tumeurs en Q3 et Q1 resp., une tres grosse metastase etendue en Q2",
  "347495": "Deux grosses tumeurs en Q3 et Q4 resp., [PAS DE METASTASES]",
  "347499": "[PAS DE PRIMAIRES], une metastase moyenne en Q1 gauche",
  "347500": "Deux tumeurs moyennes en Q2-Q3 et Q1-Q4 resp. deux metastases moyennes en Q1 gauche",
  "347501": "Une petite tumeur en Q4, [PAS DE METASTASES]",
  "347503": "[PAS DE PRIMAIRES], metastase moyenne-grosse Q1",
  "347504": "Deux tumeurs moyennes Q1 et Q2, une grosse metastase etendue Q1-Q2",
  "347505": "[PAS DE PRIMAIRES], une grosse metastase etendue Q1 avant",
  "347506": "Deux grosses tumeurs Q3 et Q4, pleins de metastases dont une grosse etendue Q1-Q2 bas et une giga etendue Q1-Q2 en haut",
  "347507": "[PAS DE PRIMAIRES], une metastase moyenne Q1 avant",
  "347509": "une tumeur mini-Godzilla plein centre, plein de metastase dont une giga etendue Q1, les autres tailles moyenne",
  "347510": "une tumeur moyenne Q3 et une grosse tumeur etendue Q4, pleins de petites metastase Q3-Q4, une grosse metastase etendue Q2, une metastase moyenne etendue Q1",
  "347511": "une tumeur mini-Godzilla plein centre, une metastase mini-Godzilla etendue avant Q1-Q2 et une grosse metastase Q1 avant",
  "347512": "deux tumeurs moyennes Q1 et Q3, une grosse metastase Q3-Q4 et une giga metastase etendue Q1-Q2 et une mince etendue Q2-Q3 et pleins de petites",
  "347514": "une tumeur Godzilla++ toutes sections, une metastase moyenne Q1 avant et une petite Q1",
  "347515": "deux moyennes tumeurs Q3 et Q4, une metastase moyenne Q2 avant -- artefact de lumiere",
  "347516": "deux tumeurs moyennes Q3 et Q4, une metastase moyenne Q3-Q4 et une grosse metastase etendue Q1-Q2",
  "347519": "UNE PETITE METASTASE SITUEE EN DEHORS DU CORPS -- deux tumeurs moyennes Q3 et Q4, une metastase moyenne Q3-Q4, trois metastases Q2 (2 petites, 1 moyenne) et une metastase Godzilla etendue Q2-Q1 avant et une grosse metastase etendue Q2-Q3",
  "347521": "une tumeur Godzilla toutes sections, trois metastases Q2 (1 grosse, 1 moyenne, 1 petite) et une moyenne Q1 -- artefacts lumineux et filaments autours du corps",
  "347523": "une tumeur moyenne Q3, une grosse metastase etendue Q1-Q2 -- artefacts lumineux et filaments autour du corps",
  "347524": "[PAS DE PRIMAIRES], une grosse metastase Q1-Q2",
  "347525": "une grosse tumeur Q4, une metastase moyenne avant Q1-Q2",
  "347528": "une tumeur moyenne Q4, une grosse metastase Q2",
  "347529": "une tumeur moyenne-petite Q2, une moyenne-grosse metastase etendue Q2",
  "347532": "[PAS DE PRIMAIRES], une metastase grosse etendue Q1",
  "347534": "une petite tumeur Q3 et une tumeur moyenne Q4, une grosse metastase Q1",
  "347538": "[PAS DE PRIMAIRES], une metastase mini-Godzilla etendue Q1",
  "347539": "une petite tumeur Q4, une grosse metastase Q1-Q2",
  "347543": "deux tumeurs moyennes Q3 et Q4, une metastase mini-Godzilla etendue Q1-Q2",
  "347544": "une tres grosse tumeur Q4 et une moyenne Q3, une metastase Godzilla Q1-Q4 etendue",
  "347546": "une grosse tumeur Q4, une metastase Godzilla Q1-Q2 etendue",
  "347547": "[PAS DE PRIMAIRES], une grosse metastase etendue Q2",
  "347549": "deux tumeurs moyennes au centre, [PAS DE METASTASES]",
  "347550": "[PAS DE PRIMAIRES], une grosse metastase etendue Q2 -- filaments autour corps",
  "347551": "une petite tumeur Q4, une metastase moyenne-grosse etendue Q1",
  "347552": "une tumeur mini-Godzilla Q1-Q2, deux metastases moyennes Q1 et Q2 -- Artefact de lumiere",
  "347553": "une tumeur Godzilla centre-Q1-Q2, une grosse metastase etendue Q1-Q2",
  "347555": "une tumeur mini-Godzilla Q1-Q4 et une grosse tumeur Q2-Q3, une grosse metastase Q2",
  "347556": "une tumeur mini-Godzilla Q4, une tres grosse metastase etendue Q1-Q2 avant",
  "347558": "une grosse tumeur Q3, [PAS DE METASTASES]",
  "347559": "une tumeur mini-Godzilla centre-Q4, trois petites metastases Q2 Q2 Q1 -- Artefacts lumineux",
  "347560": "[PAS DE PRIMAIRES], une grosse metastase etendue Q1-Q2 -- artefacts lumineux",
  "347564": "une tumeur moyenne-petite Q3, une petite metastase Q2 avant et une metastase moyenne Q1 avant",
  "347565": "[PAS DE PRIMAIRES], une grosse metastase etendue Q1 -- petits artefacts lumineux",
  "347566": "[PAS DE PRIMAIRES], une petite metastase Q1 et une moyenne-petite etendue Q1 avant",
  "347567": "une tumeur moyenne Q3, une metastase mini-Godzilla etendue Q2 et une metastase moyenne Q1",
  "347569": "[PAS DE PRIMAIRES], une metastase moyenne Q2 et une metastase moyenne Q1 et une petite avant centre",
  "347570": "[PAS DE PRIMAIRES], une grosse metastase Q1-Q2",
  "347571": "[PAS DE PRIMAIRES], deux metastase moyennes Q1 et Q2",
  "347574": "une grosse tumeur Q2, [PAS DE METASTASES]",
  "347578": "[PAS DE PRIMAIRES], deux metastases moyennes Q2 droite et Q1-Q2 avant",
  "347579": "[PAS DE PRIMAIRES], une metastase mini-Godzilla Q1-Q2 et une grosse Q1",
  "347580": "moyenne métastase milieu [PAS DE PRIMAIRE]",
  "347582": "grosse métastase avant [PAS DE PRIMAIRE]",
  "347584": "2 giga primaires milieu, métastase moyenne droite",
  "347585": "petite métastase gauche [PAS DE PRIMAIRE]",
  "347586": "moyenne primaire milieu, grosse métastase avant",
  "347588": "2 grosses primaires milieu, grosse métastase droite",
  "347589": "2 moyennes primaires milieu/avant [PAS DE METASTASE]",
  "374142": "[I] 2 petites primaires milieu, grosse métastase avant",
  "374143": "[I] 2 petites primaires milieu, petite métastase gauche",
  "374149": "[I] mini primaire [PAS DE METASTASE]",
  "374177": "[I] moyenne et petite primaires milieu, moyenne métastase avant [LAMPE JAMBE]",
  "374196": "[I] grosse primaire milieu, petite métastase avant",
  "380926": "2 minis primaires milieu, moyenne métastase droite",
  "407886": "giga primaire milieu, moyenne métastase étendue avant [LAMPE JAMBE]",
  "407887": "2 moyennes primaires milieu, petite métastase avant",
  "407888": "grosse primaire milieu, quelques minis métastases droite",
  "407890": "grosse primaire mileu/avant, plein de métastases",
  "407891": "2 moyennes primaires milieu/arrière, moyenne et petite métastases avant et droite",
  "407892": "moyenne primaire milieu, moyenne métastase droite",
  "407893": "2 moyennes primaires milieu, plein de métastases",
  "407894": "grosse primaire milieu, plein de métastases",
  "407896": "grosse primaire milieu, plein de métastases",
  "407897": "moyenne et grosse primaires milieu, plein de métastases",
  "407899": "grosse primaire avant, 2 petites métastases milieu arrière",
  "407901": "3 petites primaires milieu, 2 minis métastases bordure péritoine",
  "407902": "beaucoup de tumeurs primaires et de métastases ",
  "407903": "2 minis primaires milieu, quelques métastases surtout avant et droite",
  "407904": "2 minis primaires milieu, plein de métastases de partout dont une grosse avant",
  "407905": "moyenne métastase sur la droite [PAS DE PRIMAIRE]",
  "407906": "2 petites primaires milieu, métastase bien étendue avant et côtés",
  "407907": "beaucoup de tumeurs primaires et de métastases ",
  "407908": "une petite et moyenne primaire milieu avant, quelques minis métastases un peu de partout",
  "407909": "grosse primaire au milieu, mini métastases avant et une big à droite",
  "407910": "grosse primaire milieu avant, plein de métastases",
  "TCGA-09-0364": "giga primaire milieu [PAS DE METASTASE] (Housfield scale haute, pas beaucoup de layers)",
  "TCGA-09-0367": "2 grosses primaires avant, plein de métastases dont arrière",
  "TCGA-09-1669": "grosse primaire milieu avant [PAS DE METASTASE]",
  "TCGA-09-1674": "giga primaire milieu, plein de métastases",
  "TCGA-09-2045": "grosse primaire milieu, quelques métastases",
  "TCGA-09-2051": "grosse primaire milieu, plein de métastases",
  "TCGA-09-2053": "moyenne primaire milieu, petite métastase droite",
  "TCGA-09-2054": "[PAS DE LABEL + RESPIRATION SUPER MARQUEE]",
  "TCGA-13-0724": "moyenne métastase avant [PAS DE PRIMAIRE]",
  "TCGA-13-0761": "grosse primaire milieu, plein de métastases dont milieu/arrière",
  "TCGA-13-0762": "mauvaise segmentation",
  "TCGA-13-0768": "2 petites primaires milieu, plein de métastases",
  "TCGA-13-0793": "moyenne et grosse primaires milieu, plein de métastases",
  "TCGA-13-0794": "giga primaire milieu/avant, plein de métastases",
  "TCGA-13-0799": "[I] 2 grosses primaires milieu [PAS DE METASTASE]",
  "TCGA-13-0883": "grosse primaire avant, 2 petites métastases avant",
  "TCGA-13-0904": "[I] 2 petites primaires milieu, métastase avant étendue",
  "TCGA-13-0911": "moyenne primaire milieu/avant, petite métastase gauche (Housfield scale haute, sorte de parasite sur le scan)",
  "TCGA-13-0920": "giga primaire, plein de métastases",
  "TCGA-13-0924": "2 petites primaires, plein de métastases",
  "TCGA-13-1405": "[I] 2 petites primaires, grosse métastase étendue avant",
  "TCGA-13-1408": "grosse métastase gauche [PAS DE PRIMAIRE]",
  "TCGA-13-1411": "giga primaire milieu, grosse métastase étendue avant/droite [LAMPE JAMBE]",
  "TCGA-13-1412": "2 moyennes primaires milieu/avant, quelques métastases gauche",
  "TCGA-13-1488": "[I] petite et grosse primaires milieu, mini métastase droite",
  "TCGA-13-1499": "[I] petite métastase avant [PAS DE PRIMAIRE]",
  "TCGA-13-1507": "[I] 2 petites primaires milieu, moyenne et grosse métastases avant",
  "TCGA-13-1509": "petite et moyenne primaires milieu, moyenne métastase étendue droite [LAMPE JAMBE]",
  "TCGA-13-1511": "[I] 2 moyennes primaires milieu, grosse métastase étendue gauche",
  "TCGA-13-2060": "petite et moyenne primaires milieu/avant, petites métastases avant et gauche",
  "TCGA-24-1418": "2 petites primaires milieu, plein de métastases intéressantes",
  "TCGA-24-1423": "petite et grosse primaires milieu/avant, plein de métastases",
  "TCGA-24-1427": "2 petites primaires milieu, plein de métastases",
  "TCGA-24-1614": "[I] 2 petites métastases droite et gauche [11 slices] [PAS DE PRIMAIRE]",
  "TCGA-24-1616": "2 petites primaires milieu, plein de métastases",
  "TCGA-24-2254": "giga primaire avant, plein de métastases",
  "TCGA-25-1313": "petite et mini primaires milieu, plein de métastases (Housfield scale haute)",
  "TCGA-25-1623": "petite et mini primaires milieu, quelques métastases",
  "TCGA-25-1631": "grosse primaire milieu [PAS DE METASTASE] (Housfield scale haute)",
  "TCGA-25-1635": "grosse et moyenne primaires milieu, plein de métastases",
  "TCGA-30-1891": "2 petites primaires milieu, plein de métastases",
  "TCGA-61-1900": "grosse primaire milieu, petite métastase droite",
  "TCGA-61-1906": "[I] beaucoup de tumeurs primaires et de métastases ",
  "TCGA-61-1910": "moyenne primaire milieu [PAS DE METASTASE]",
  "TCGA-61-1911": "grosse primaire avant [PAS DE METASTASE]",
  "TCGA-61-2003": "2 moyennes primaires milieu, plein de métastases (une sorte de lumière au dessus du scan)",
  "TCGA-61-2009": "grosse et petite primaire milieu, plein de métastases",
  "TCGA-61-2016": "[I] 2 petites primaires milieu, plein de métastases intéressantes",
  "TCGA-61-2018": "grosse et petite primaires milieu [PAS DE METASTASE]",
  "TCGA-61-2087": "grosse et petite primaires milieu, plein de métastases",
}


def create_folds_dataframe(
  to_exclude: list["str"], n_folds: int, seed: int
) -> pd.DataFrame:
  all_scan_ids = [e for e in list(annotations.keys()) if e not in to_exclude]

  total_scans = len(all_scan_ids)

  n_scan_for_test = int(total_scans * 0.1)
  n_scan_for_fold = total_scans - n_scan_for_test

  base_fold_size = n_scan_for_fold // n_folds
  remainder = n_scan_for_fold % n_folds

  fold_sizes = [
    base_fold_size + 1 if i < remainder else base_fold_size for i in range(n_folds)
  ]

  random.seed(seed)
  random.shuffle(all_scan_ids)

  data = []
  start_index, end_index = 0, 0
  for i in range(n_folds):
    fold_size = fold_sizes[i]
    end_index = start_index + fold_size
    current_fold = all_scan_ids[start_index:end_index]
    data.extend(list(zip(current_fold, [i] * len(current_fold), strict=False)))
    start_index = end_index

  data.extend(
    list(
      zip(all_scan_ids[end_index:], [-1] * len(all_scan_ids[end_index:]), strict=False)
    )
  )

  return pd.DataFrame(data=data, columns=["path", "fold"])
